# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站
# 网站标题
title: Blog Of Kifary

# 网站副标题
subtitle: 技术改变命运

# 网站描述
description: 专注于 IT 技术分享

# 网站的关键词。支持多个关键词。
keywords: iOS

# 您的名字
author: Kifary

# 网站使用的语言。对于简体中文用户来说，使用不同的主题可能需要设置成不同的值，请参考你的主题的文档自行设置，常见的有 zh-Hans和 zh-CN。
language:
  - zh-CN
  - en

# 网站时区。Hexo 默认使用您电脑的时区。请参考 时区列表 进行设置，如 America/New_York, Japan, 和 UTC 。一般的，对于中国大陆地区可以使用 Asia/Shanghai。
timezone:

# 网址
# 网址, 必须以 http:// 或 https:// 开头
url: https://swiftbman.github.io/hexo-kifary-blog

# 网站根目录
root: /hexo-kifary-blog/

# 文章的 永久链接 格式 https://hexo.io/zh-cn/docs/permalinks
permalink: :lang/:year/:month/:day/:title/

# 永久链接中各部分的默认值
permalink_defaults:
  lang: zh

# 改写 permalink 的值来美化 URL
pretty_urls:
  # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_index: true
  # 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)
  trailing_html: true

# 目录
# 资源文件夹，这个文件夹用来存放内容。
source_dir: source

# 公共文件夹，这个文件夹用于存放生成的站点文件。
public_dir: public

# 标签文件夹
tag_dir: tags

# 归档文件夹
archive_dir: archives

# 分类文件夹
category_dir: categories

# Include code 文件夹，source_dir 下的子目录
code_dir: downloads/code

# 国际化（i18n）文件夹
i18n_dir: :lang

# 跳过指定文件的渲染。
# 匹配到的文件将会被不做改动地复制到 public 目录中。
# 您可使用 glob 表达式来匹配路径。
# https://github.com/micromatch/micromatch#extended-globbing
skip_render:

# 文章
# 新文章的文件名称
new_post_name: :lang/:title.md

# 预设布局
# Hexo 有三种默认布局：post、page 和 draft
default_layout: post

# 在中文和英文之间加入空格
titlecase: false

# 在新标签中打开链接
external_link:
  enable: true # 在新标签中打开链接
  field: site # 对整个网站（site）生效或仅对文章（post）生效
  exclude: "" # 需要排除的域名。主域名和子域名如 www 需分别配置

# 把文件名称转换为 (1) 小写或 (2) 大写
filename_case: 0

# 显示草稿
render_drafts: false

# 启动 Asset 文件夹
# https://hexo.io/zh-cn/docs/asset-folders
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true

# 把链接改为与根目录的相对位址
relative_link: false

# 显示未来的文章
future: true

# 代码块的设置, 请参考 Highlight.js 进行设置
# https://hexo.io/docs/syntax-highlight#Highlight-js
highlight:
  enable: true
  line_number: true
  auto_detect: false
  line_threshold: 0
  tab_replace: ""
  exclude_languages:
    - example
    - mermaid
  wrap: true
  hljs: false

# 代码块的设置, 请参考 PrismJS 进行设置
# https://hexo.io/docs/syntax-highlight#PrismJS
prismjs:
  enable: false
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# 分类 & 标签
# 默认分类
default_category: uncategorized
# 分类别名
category_map:
# 标签别名
tag_map:

# 日期 / 时间格式
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
# 日期格式
date_format: YYYY-MM-DD
# 时间格式
time_format: HH:mm:ss
# 当 Front Matter 中没有指定 updated 时 updated 的取值
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# 分页
# 每页显示的文章量 (0 = 关闭分页功能)
per_page: 10
# 分页目录
pagination_dir: page

# 包括或不包括目录和文件
## include:/exclude: options only apply to the 'source/' folder
# Hexo 默认会不包括 source/ 下的文件和文件夹（包括名称以下划线和 . 开头的文件和文件夹，Hexo 的 _posts 和 _data 等目录除外）。
# 通过设置此字段将使 Hexo 处理他们并将它们复制到 source 目录下。
include:
# Hexo 不包括 source/ 下的这些文件和目录
exclude:
# Hexo 会忽略整个 Hexo 项目下的这些文件夹或文件
ignore:

# 扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# 当前主题名称。值为false时禁用主题
# next、icarus、fluid、butterfly
theme: next

# 主题的配置文件。在这里放置的配置会覆盖主题目录下的 _config.yml 中的配置
theme_config:

# 部署
## Docs: https://hexo.io/docs/one-command-deployment
# 部署部分的设置
deploy:
  type: git # 设置发布类型，如git，rsync
  repo: https://github.com/SwiftBMan/hexo-kifary-blog.git
  branch: "hexo-kifary-blog"
  message: Site updated at {{ now("YYYY-MM-DD HH:mm:ss") }}

# Metadata elements
# Meta generator 标签。 值为 false 时 Hexo 不会在头部插入该标签
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# hexo-generator-sitemap
# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path:
    - sitemap.xml
    - sitemap.txt
  template:
  template_txt:
  rel: false
  tags: true
  categories: true

tag_generator:
  enable_index_page: false
# three:
#   enable: true
#   defer: true
#   cdn:
#   waves:
#     enable: true
#     cdn:
#   lines:
#     enable: false
#     cdn:
#   sphere:
#     enable: false
#     cdn:
