# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site 网站
title: JokerZheng of Blog       # 网站标题
subtitle:     Life doesn't get easier, you just get stronger.        # 网站副标题
description:  Life doesn't get easier, you just get stronger.    # 网站描述
author: JokerZheng              # 您的名字
language:  zh-CN              # 网站使用的语言 旧的zh-Hans

timezone:         # 网站时区。Hexo 默认使用您电脑的时区。时区列表。比如说：America/New_York, Japan, 和 UTC 。

# URL 网址
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://swiftbman.github.io                      # 网址
root: /                                       # 网站根目录
permalink: :year/:month/:day/:title/          # 文章的 永久链接 格式
permalink_defaults:                           # 永久链接中各部分的默认值

# Directory # 目录
source_dir: source        # 资源文件夹，这个文件夹用来存放内容。
public_dir: public        # 公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags             # 标签文件夹
archive_dir: archives     # 归档文件夹
category_dir: categories  # 分类文件夹
code_dir: downloads/code  # Include code 文件夹
i18n_dir: :lang           # 国际化（i18n）文件夹
skip_render:              # 跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。

# Writing 文章
new_post_name: :title.md # File name of new posts     # 新文章的文件名称
default_layout: post                                  # 预设布局
titlecase: false # Transform title into titlecase     # 把标题转换为 title case
external_link: true # Open external links in new tab  # 在新标签中打开链接
filename_case: 0                                      # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false                                  # 显示草稿
post_asset_folder: true                              # 启动 Asset 文件夹
relative_link: false                                  # 把链接改为与根目录的相对位址
future: true                                          # 显示未来的文章
highlight:                                            # 代码块的设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting 
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
  
# Category & Tag  分类 & 标签
default_category: uncategorized # 默认分类
category_map:                   # 分类别名	
tag_map:                        # 标签别名

# Date / Time format 日期 / 时间格式
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD         # 日期格式
time_format: HH:mm:ss           # 日期格式

# 本地搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Pagination 分页
## Set per_page to 0 to disable pagination
per_page: 10                    # 每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page            # 分页目录


# Extensions 扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-reloaded                                  # 当前主题名称。值为false时禁用主题，旧的主题next



# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git # 设置发布类型，如git，rsync
  repo: git@github.com:SwiftBMan/SwiftBMan.github.io.git
  branch: master                                                
  message: Site updated at {{ now("YYYY-MM-DD HH:mm:ss") }} 

# aplayer
aplayer:
  meting: true

image_stream:
  jquery: false
  jquery_lazyload: false
  img_placeholder: http://ww4.sinaimg.cn/large/e724cbefgw1etyppy7bgwg2001001017.gif

# hexo-helper-live2d
live2d:
  enable: false
  # pluginRootPath: live2dw/ # Root path of plugin to be on the site (Relative)
  # pluginJsPath: lib/ # JavaScript path related to plugin's root (Relative)
  # pluginModelPath: assets/ # Relative model path related to plugin's root (Relative)
  model:
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
    # use: ./packages/live2d-widget-model-chitose
    # use: ./packages/live2d-widget-model-epsilon2_1
    # use: ./packages/live2d-widget-model-gf
    # use: ./packages/live2d-widget-model-haru/01
    # use: ./packages/live2d-widget-model-haru/02
    # use: ./packages/live2d-widget-model-haruto
    # use: ./packages/live2d-widget-model-hibiki
    # use: ./packages/live2d-widget-model-hijiki # 猫
    # use: ./packages/live2d-widget-model-izumi
    # use: ./packages/live2d-widget-model-koharu
    # use: ./packages/live2d-widget-model-miku
    # use: ./packages/live2d-widget-model-ni-j
    # use: ./packages/live2d-widget-model-nico
    # use: ./packages/live2d-widget-model-nietzsche
    # use: ./packages/live2d-widget-model-nipsilon
    # use: ./packages/live2d-widget-model-shizuku
    # use: ./packages/live2d-widget-model-tororo
    # use: ./packages/live2d-widget-model-tsumiki
    use: ./packages/live2d-widget-model-unitychan 
    # use: ./packages/live2d-widget-model-wanko
    # use: ./packages/live2d-widget-model-z16
  display:
    superSample: 2
    width: 75
    height: 150
    position: left
    hOffset: 0
    vOffset: 0
  mobile:
    show: true
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

# 代码压缩 github.com/chenzhutian/hexo-all-minifier
all_minifier: true
html_minifier:
  enable: true
  ignore_error: false
  exclude:
  
css_minifier:
  enable: true
  exclude: 
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'
image_minifier: 
  enable: false # 图片不压缩
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

# Hexo 插件，解决 disqus 不能访问的反向代理
# disqus_proxy:
#   shortname: ciqu
#   username: ciqu
#   host: disqus-proxy.ycwalker.com
#   port: 443